[PHP]
; Memory limit
memory_limit=256M
upload_max_filesize=100M
post_max_size=100M

; Execution time
max_execution_time=60
max_input_time=60

; Error reporting (development version)
display_errors=On
display_startup_errors=On
error_reporting=E_ALL

; Default Timezone
date.timezone=UTC

; Session configuration
session.cookie_secure=On
session.cookie_httponly=On
session.cookie_samesite=Lax
